version: '3'
services:
    srv:
        image: node:alpine
        working_dir: /app
        command: npm run start:dev
        volumes:
            - $PWD:/app
        ports:
            - 3000:3000
        links:
            - bdd
    bdd:
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=secret
